'use client'

import { useState } from 'react'
import { Check, Edit3, FolderPlus, MoreHorizontal, Plus, Search, ShoppingBag, Star, X } from 'lucide-react'
import { Sidebar, Topbar } from './shamsiya-dashboard'

const initialCategories = [
  { name: 'Main Dishes', description: 'Signature meals and hearty plates', count: 18, status: 'Active', emoji: '🍛', tone: 'orange', sales: '₵48,250', change: '+12.5%' },
  { name: 'Rice Dishes', description: 'Jollof, fried rice, mandi and more', count: 12, status: 'Active', emoji: '🍚', tone: 'sand', sales: '₵32,180', change: '+8.4%' },
  { name: 'Grills & Suya', description: 'Charcoal grills and spicy skewers', count: 8, status: 'Active', emoji: '🥩', tone: 'brown', sales: '₵21,740', change: '+14.2%' },
  { name: 'Snacks', description: 'Small bites, sides, and street food', count: 6, status: 'Active', emoji: '🍌', tone: 'yellow', sales: '₵9,620', change: '+5.8%' },
  { name: 'Drinks', description: 'Fresh juices, sobolo, and coolers', count: 4, status: 'Active', emoji: '🧃', tone: 'green', sales: '₵7,440', change: '+10.1%' },
  { name: 'Desserts', description: 'Sweet finishes for every order', count: 3, status: 'Inactive', emoji: '🍰', tone: 'rose', sales: '₵3,180', change: '+2.4%' },
]
function CategoryForm({ onClose, onSave }: { onClose: () => void; onSave: (name: string) => void }) { const [name, setName] = useState(''); return <div className="modal-layer" role="presentation" onClick={onClose}><div className="assign-modal category-form-modal" role="dialog" aria-modal="true" aria-labelledby="category-form-title" onClick={e => e.stopPropagation()}><div className="drawer-heading"><div><span className="eyebrow">Menu organization</span><h2 id="category-form-title">Add category</h2></div><button className="icon-button" onClick={onClose} aria-label="Close category form"><X /></button></div><p className="modal-copy">Create a clear section for customers to browse in the menu.</p><label className="field-label">Category name<input className="food-input" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Breakfast" /></label><label className="field-label">Description<textarea className="food-input" rows={3} placeholder="A short description for the category" /></label><label className="field-label">Status<select className="food-input"><option>Active</option><option>Inactive</option></select></label><button className="primary-button" disabled={!name.trim()} onClick={() => onSave(name.trim())}><Plus /> Add category</button></div></div> }
export default function ShamsiyaCategories() { const [open, setOpen] = useState(false); const [categories, setCategories] = useState(initialCategories); const [formOpen, setFormOpen] = useState(false); const [query, setQuery] = useState(''); const filtered = categories.filter(category => `${category.name} ${category.description}`.toLowerCase().includes(query.toLowerCase())); return <div className="dashboard-app"><Sidebar open={open} setOpen={setOpen} /><div className="app-canvas"><Topbar setOpen={setOpen} /><main className="main-content categories-main"><div className="page-heading overview-heading"><div><div className="eyebrow"><span className="live-dot" /> Menu management</div><h1>Categories</h1><p>Organize foods into clear, discoverable menu sections.</p></div><div className="heading-actions"><button className="secondary-button"><Search /> Manage order</button><button className="primary-button" onClick={() => setFormOpen(true)}><FolderPlus /> Add category</button></div></div><section className="category-summary"><div><strong>{categories.length}</strong><span>Menu categories</span></div><div><strong>{categories.reduce((sum, category) => sum + category.count, 0)}</strong><span>Foods organized</span></div><div><strong>{categories.filter(category => category.status === 'Active').length}</strong><span>Active sections</span></div><div className="category-search"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search categories..." aria-label="Search categories" /></div></section><section className="category-grid">{filtered.map(category => <article className="category-card" key={category.name}><div className={`category-hero ${category.tone}`}><span>{category.emoji}</span><button className="category-more" aria-label={`More actions for ${category.name}`}><MoreHorizontal /></button></div><div className="category-card-content"><div className="category-card-heading"><div><h2>{category.name}</h2><p>{category.description}</p></div><span className={`status-badge ${category.status === 'Active' ? 'status-success' : 'status-pending'}`}><span />{category.status}</span></div><div className="category-metrics"><div><strong>{category.count}</strong><span>Foods</span></div><div><strong>{category.sales}</strong><span>Revenue</span></div><div><strong><Star /> {category.change}</strong><span>Growth</span></div></div><div className="category-card-footer"><button className="text-button"><ShoppingBag /> View foods</button><button className="icon-button" aria-label={`Edit ${category.name}`}><Edit3 /></button></div></div></article>)}</section>{formOpen && <CategoryForm onClose={() => setFormOpen(false)} onSave={name => { setCategories([...categories, { name, description: 'A new menu section', count: 0, status: 'Active', emoji: '🍽️', tone: 'orange', sales: '₵0', change: 'New' }]); setFormOpen(false) }} />}</main></div></div> }
